version: '2'
services:
  web:
    build: docker/web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/
  sql:
      build: docker/sql
      ports:
        - "3306:3306"
      volumes:
        - ./docker/sql/data:/var/lib/mysql-57